<?php

require_once dirname(__FILE__) . '/../Login.php';
require_once dirname(__FILE__) . '/../BruteForce.php';

/**
 * Test class for Login.
 * Generated by PHPUnit on 2012-01-05 at 16:00:17.
 */
class LoginTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Login
     */
    protected $object;
    protected $bruteObj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Login('oliver','christ');
        $this->bruteObj = new BruteForce('oliver', 'oliver');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate() {
        $this->assertTrue($this->object->authenticate('oliver', 'christ'));
    }
    
    public function testAuthenticate2() {
        $this->assertFalse($this->object->authenticate('xxx', 'yyy'));
    }
    public function testBruteForce() {
        $this->assertTrue($this->bruteObj->force());
    }
}

?>
